server:
  port: 8500
eureka:
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka
#    fetch-registry: false
#    register-with-eureka: false
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
    appname: conserver
spring:
  application:
    name: conserver
  security:
      basic:
        enabled: true
      user:
        name: root #用户名和密码，等会访问的时候，会要求你登录，服务注册的时候也需要带着用户名和密码
        password: booszy
  cloud:
    config:
      discovery:
        enabled: true
        service-id: conserver
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/chrole123/shan.git
          searchPaths: /**
      profile: master
      username: chrole123
      password: sj574750

feign:
  hystrix:
    enabled: true
